repository:
  url: ""
  sshPrivateKey: ""

application:
  name: django-app
  namespace: argocd
  project: default
  sourceRepoURL: ""
  targetRevision: final-project
  chartPath: charts/django-app
  destination: https://kubernetes.default.svc
  destNamespace: django-app
  imageRepository: ""
  postgresHost: ""
