replicaCount: 2

image:
  repository: REPLACE_WITH_ECR_REPOSITORY_URL
  tag: "9f7eea1"
  pullPolicy: Always

service:
  type: LoadBalancer
  port: 80
  targetPort: 8000

config:
  DJANGO_DEBUG: "False"
  DJANGO_ALLOWED_HOSTS: "*"
  POSTGRES_DB: "django_db"
  POSTGRES_USER: "dbadmin"
  POSTGRES_HOST: "REPLACE_WITH_RDS_ENDPOINT"
  POSTGRES_PORT: "5432"

secret:
  create: false
  existingSecret: django-app-secret
  DJANGO_SECRET_KEY: ""
  POSTGRES_PASSWORD: ""

autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 6
  targetCPUUtilizationPercentage: 70

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 500m
    memory: 512Mi
